Update concrete section definitions
robbievanleeuwen/section-properties pull request #202
Opened 2022-03-01 11:54 UTC by robbievanleeuwen

New concrete section definitions:
- Now correctly subtracts area for reinforcement, i.e. `geom = (geom - bar) + bar
- Added option for adding top reinforcement to rectangular and tee sections
- Added option for added circular concrete area for circular section

2022-03-01 12:01 UTC, robbievanleeuwen commented
(seems to be an issue with new version on `rhino3dm` released ~1hr ago?)

2022-03-07 07:06 UTC, connorferster approved these changes

2022-03-07 07:08 UTC, connorferster requested changes
In the interest of improving test coverage, would you be up for writing a basic test for each the concrete sections?  Something just validating that the geometry expected is what is indeed being produced :)

2022-03-07 07:35 UTC, robbievanleeuwen commented
@connorferster just adding some simple area checking tests :)

2022-03-07 16:14 UTC, merged