Proposed fix for non-recognized holes
robbievanleeuwen/section-properties pull request #297
Opened 2023-09-30 19:05 UTC by connorferster

When the geometries resulting from an operation result in a MultiPolygon that only touch at points, a hole is not recognized in shapely but it is "recognized" by humans. To fix this problem, the hole needs to be recognized by shapely as part of a Polygon. One solution to fix this would be to buffer the geometry by a very small amount to force this switch from MultiPolygon to Polygon.

2023-10-01 04:13 UTC, robbievanleeuwen commented
Looks good @connorferster, thanks! Just a small fix required by `flake8` to be more pythonic:

```
src/sectionproperties/pre/geometry.py:2387:10: N806 variable 'SCALE_CONSTANT' in function should be lowercase
```

Will merge after this change :)

2023-10-01 04:14 UTC, robbievanleeuwen commented on src/sectionproperties/pre/geometry.py
> +        SCALE_CONSTANT = 1e-9
`scale_constant = 1e-9`

2023-10-01 04:15 UTC, robbievanleeuwen requested changes
Looks good @connorferster, thanks! Just a small fix required by flake8 to be more pythonic:
```
src/sectionproperties/pre/geometry.py:2387:10: N806 variable 'SCALE_CONSTANT' in function should be lowercase
```
Will merge after this change :)

2023-10-01 04:24 UTC, connorferster commented
Hmm...maybe I should put the scale constant outside of the function then? As per PEP8, constants should be all caps. I will try moving it to the module level (which I prefer not to do because then it will be visible during the module imports) to see if that makes flake8 happy.

2023-10-01 04:29 UTC, robbievanleeuwen commented
Thanks @connorferster that should probably work - note `N806` is "variable in function should be lowercase"

PEP8 says "Constants are usually defined on a module level", I guess that's what is making the linter upset.

2023-10-02 11:08 UTC, robbievanleeuwen approved these changes

2023-10-02 11:17 UTC, merged