Add numba, pardiso
robbievanleeuwen/section-properties pull request #324
Opened 2023-10-05 04:55 UTC by TLCFEM

1. Further @jit shape function computation.
2. Provide alternative to use pardiso as sparse solver.

The default superlu solver is unbearably slow on large systems. With this PR, the warping computation is now ~10% of the time required by v2.1.5.

2023-10-06 13:58 UTC, TLCFEM commented on src/sectionproperties/analysis/fea.py
> +@njit(cache=True, nogil=True)
Making those utilities pure numerical so that they can be jited.

2023-10-06 13:59 UTC, TLCFEM commented on src/sectionproperties/analysis/fea.py
> +h_inv = np.array(
Avoid repeatedly creating and destroying this constant matrix.

2023-10-06 13:59 UTC, TLCFEM commented on src/sectionproperties/analysis/section.py
> -                ixx_c + iyy_c - omega.dot(k_lg[:-1, :-1].dot(np.transpose(omega)))
Overcomplex computation as U is the solution to KU=F

2023-10-06 14:05 UTC, TLCFEM commented
@robbievanleeuwen Should be ready, please check it at your convenience.

2023-10-09 11:14 UTC, robbievanleeuwen commented
Thanks again for your hard work @TLCFEM - I will try to have a look at this in the next few days :)

2023-10-11 06:58 UTC, robbievanleeuwen requested changes
This looks really good @TLCFEM, thanks again!

Running the newly added benchmarks, I got a significantly faster runtime for the heaviest warping analysis on my machine with the `paradiso` solver (4.6 secs vs. 1.6secs), well done!

The only thing apart from the minor comments is a warning that is printed when running the tests:

```
tests/analysis/test_stress.py::test_stress_runtime_errors
  /home/runner/work/section-properties/section-properties/src/sectionproperties/analysis/fea.py:1114: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (Array(float64, 2, 'C', True, aligned=True), Array(float64, 1, 'A', False, aligned=True))
    return h_inv.dot(w)
```

I'm never used `numba` before so not sure if this is worth addressing?

2023-10-11 06:58 UTC, robbievanleeuwen commented on pyproject.toml
> +numpy = "^1.25.2"
Could you put a comment here stating the reason for the downgrade so I can remember to check this if `numba` allows further `numpy` updates.

```
e.g. numpy = "^1.25.2"  # numba requires numpy <1.26
```

2023-10-11 06:58 UTC, robbievanleeuwen commented on pyproject.toml
> +pypardiso = { version = "^0.4.2", optional = true }
I agree that it is a good idea to make it optional, making it a core dependency will also mean that it needs to be downloaded and installed for CI (e.g. tests, docs build).

2023-10-11 06:58 UTC, robbievanleeuwen commented on docs/installation.rst
> +The ``PARDISO`` solver is a much faster alternative, but it requires the installation of the ``MKL`` library, which takes a lot of disk space.
This section reads really well, thanks! I would just suggest providing a link the the pypardiso GitHub page so users can easily decide whether or not they would like to install this. For example:

> The ``PARDISO`` solver is a much faster alternative (see [PyPardiso](https://github.com/haasad/PyPardisoProject)), but it requires...

2023-10-11 06:58 UTC, robbievanleeuwen commented on src/sectionproperties/analysis/fea.py
>          sig_zz_n = n * np.ones(6) * self.material.elastic_modulus / ea
Probably make this ``np.ones(n_points)`` for consistency.

2023-10-11 06:58 UTC, robbievanleeuwen commented on src/sectionproperties/analysis/section.py
> +            coords = self._mesh_nodes[node_ids, :].transpose()
Nice!

2023-10-11 09:24 UTC, TLCFEM commented
> This looks really good @TLCFEM, thanks again!
> 
> Running the newly added benchmarks, I got a significantly faster runtime for the heaviest warping analysis on my machine with the `paradiso` solver (4.6 secs vs. 1.6secs), well done!
> 
> The only thing apart from the minor comments is a warning that is printed when running the tests:
> 
> ```
> tests/analysis/test_stress.py::test_stress_runtime_errors
>   /home/runner/work/section-properties/section-properties/src/sectionproperties/analysis/fea.py:1114: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (Array(float64, 2, 'C', True, aligned=True), Array(float64, 1, 'A', False, aligned=True))
>     return h_inv.dot(w)
> ```
> 
> I'm never used `numba` before so not sure if this is worth addressing?

Not a great concern as this omega is passed in as a view of some other matrix, which happen to be row major that causes non-contiguous arrays. To suppress this warning, either transpose the following:

```py
        sig_zxy_mzz_gp = np.zeros((n_points, 2))
        sig_zxy_vx_gp = np.zeros((n_points, 2))
        sig_zxy_vy_gp = np.zeros((n_points, 2))
```

or replace dot with matmul. I chose the latter.

2023-10-11 10:29 UTC, robbievanleeuwen approved these changes

2023-10-11 10:29 UTC, merged